# Key material that is used in several places:
#   - admin service gRPC TLS
#   - signing all the auth tokens we create
#   - checking signature on policy files (so must match that used in compiler)
#   - (but not yet for...) thrift TLS
vs_cert: node-cert.pem
vs_key: node.key


# Also missing is root certificate used to check the certs from connecting
# nodes.

