
# This is the noise PK certificate used by the visa service adatper.
# For now the visa service only uses this to get its CN value, which
# must match the ZPL visaservice.provider setting.
adapter_cert: conform-adapter-vs-cert.pem

root_ca: conform-ca-cert.pem

# For milestone2 you need connect validation turned off.
disable_connect_validation: true

# This RSA cert and key are left over from prototype and still used for:
#  - admin service gRPC connection
#  - signing JWT auth tokens
#  - checking signature on policy file
#
vs_cert: zpr-rsa-cert.pem
vs_key: zpr-rsa-key.pem

# verbose: true

