// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: policy.proto

package polio

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SvcT int32

const (
	SvcT_SVCT_UNUSED     SvcT = 0
	SvcT_SVCT_DEF        SvcT = 1
	SvcT_SVCT_AUTH       SvcT = 2 // visa service facing auth service
	SvcT_SVCT_DECORATOR  SvcT = 3
	SvcT_SVCT_ACTOR_AUTH SvcT = 4 // actor facing auth service
)

// Enum value maps for SvcT.
var (
	SvcT_name = map[int32]string{
		0: "SVCT_UNUSED",
		1: "SVCT_DEF",
		2: "SVCT_AUTH",
		3: "SVCT_DECORATOR",
		4: "SVCT_ACTOR_AUTH",
	}
	SvcT_value = map[string]int32{
		"SVCT_UNUSED":     0,
		"SVCT_DEF":        1,
		"SVCT_AUTH":       2,
		"SVCT_DECORATOR":  3,
		"SVCT_ACTOR_AUTH": 4,
	}
)

func (x SvcT) Enum() *SvcT {
	p := new(SvcT)
	*p = x
	return p
}

func (x SvcT) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SvcT) Descriptor() protoreflect.EnumDescriptor {
	return file_policy_proto_enumTypes[0].Descriptor()
}

func (SvcT) Type() protoreflect.EnumType {
	return &file_policy_proto_enumTypes[0]
}

func (x SvcT) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SvcT.Descriptor instead.
func (SvcT) EnumDescriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{0}
}

type ICMPT int32

const (
	ICMPT_ICMPT_UNUSED ICMPT = 0
	ICMPT_ICMPT_REQREP ICMPT = 1
	ICMPT_ICMPT_ONCE   ICMPT = 2
)

// Enum value maps for ICMPT.
var (
	ICMPT_name = map[int32]string{
		0: "ICMPT_UNUSED",
		1: "ICMPT_REQREP",
		2: "ICMPT_ONCE",
	}
	ICMPT_value = map[string]int32{
		"ICMPT_UNUSED": 0,
		"ICMPT_REQREP": 1,
		"ICMPT_ONCE":   2,
	}
)

func (x ICMPT) Enum() *ICMPT {
	p := new(ICMPT)
	*p = x
	return p
}

func (x ICMPT) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ICMPT) Descriptor() protoreflect.EnumDescriptor {
	return file_policy_proto_enumTypes[1].Descriptor()
}

func (ICMPT) Type() protoreflect.EnumType {
	return &file_policy_proto_enumTypes[1]
}

func (x ICMPT) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ICMPT.Descriptor instead.
func (ICMPT) EnumDescriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{1}
}

type AttrOpT int32

const (
	AttrOpT_UNUSED   AttrOpT = 0
	AttrOpT_EQ       AttrOpT = 1
	AttrOpT_NE       AttrOpT = 2
	AttrOpT_HAS      AttrOpT = 7
	AttrOpT_EXCLUDES AttrOpT = 8
)

// Enum value maps for AttrOpT.
var (
	AttrOpT_name = map[int32]string{
		0: "UNUSED",
		1: "EQ",
		2: "NE",
		7: "HAS",
		8: "EXCLUDES",
	}
	AttrOpT_value = map[string]int32{
		"UNUSED":   0,
		"EQ":       1,
		"NE":       2,
		"HAS":      7,
		"EXCLUDES": 8,
	}
)

func (x AttrOpT) Enum() *AttrOpT {
	p := new(AttrOpT)
	*p = x
	return p
}

func (x AttrOpT) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AttrOpT) Descriptor() protoreflect.EnumDescriptor {
	return file_policy_proto_enumTypes[2].Descriptor()
}

func (AttrOpT) Type() protoreflect.EnumType {
	return &file_policy_proto_enumTypes[2]
}

func (x AttrOpT) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AttrOpT.Descriptor instead.
func (AttrOpT) EnumDescriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{2}
}

type OpCodeT int32

const (
	OpCodeT_OP_Nop      OpCodeT = 0
	OpCodeT_OP_Register OpCodeT = 1 // args are (NAME, TYPE, ENDPOINTS) type (STRING, SvcT, STRING)
	OpCodeT_OP_SetFlag  OpCodeT = 2
	OpCodeT_OP_SetCfg   OpCodeT = 3
)

// Enum value maps for OpCodeT.
var (
	OpCodeT_name = map[int32]string{
		0: "OP_Nop",
		1: "OP_Register",
		2: "OP_SetFlag",
		3: "OP_SetCfg",
	}
	OpCodeT_value = map[string]int32{
		"OP_Nop":      0,
		"OP_Register": 1,
		"OP_SetFlag":  2,
		"OP_SetCfg":   3,
	}
)

func (x OpCodeT) Enum() *OpCodeT {
	p := new(OpCodeT)
	*p = x
	return p
}

func (x OpCodeT) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OpCodeT) Descriptor() protoreflect.EnumDescriptor {
	return file_policy_proto_enumTypes[3].Descriptor()
}

func (OpCodeT) Type() protoreflect.EnumType {
	return &file_policy_proto_enumTypes[3]
}

func (x OpCodeT) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OpCodeT.Descriptor instead.
func (OpCodeT) EnumDescriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{3}
}

type FlagT int32

const (
	FlagT_F_UNUSED      FlagT = 0
	FlagT_F_NODE        FlagT = 1
	FlagT_F_VISASERVICE FlagT = 2 // set by adapter hosting a visa service instance
	FlagT_F_VS_DOCK     FlagT = 3 // set by a node a visa service can dock to
)

// Enum value maps for FlagT.
var (
	FlagT_name = map[int32]string{
		0: "F_UNUSED",
		1: "F_NODE",
		2: "F_VISASERVICE",
		3: "F_VS_DOCK",
	}
	FlagT_value = map[string]int32{
		"F_UNUSED":      0,
		"F_NODE":        1,
		"F_VISASERVICE": 2,
		"F_VS_DOCK":     3,
	}
)

func (x FlagT) Enum() *FlagT {
	p := new(FlagT)
	*p = x
	return p
}

func (x FlagT) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FlagT) Descriptor() protoreflect.EnumDescriptor {
	return file_policy_proto_enumTypes[4].Descriptor()
}

func (FlagT) Type() protoreflect.EnumType {
	return &file_policy_proto_enumTypes[4]
}

func (x FlagT) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FlagT.Descriptor instead.
func (FlagT) EnumDescriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{4}
}

// PolicyContainer is what is sent to a node (produced by the compiler)
type PolicyContainer struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ContainerVersion uint32                 `protobuf:"varint,1,opt,name=container_version,json=containerVersion,proto3" json:"container_version,omitempty"`
	PolicyDate       string                 `protobuf:"bytes,2,opt,name=policy_date,json=policyDate,proto3" json:"policy_date,omitempty"`             // copied out of policy as a convenience
	PolicyVersion    uint64                 `protobuf:"varint,3,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`   // copied out of policy as a convenience
	PolicyRevision   string                 `protobuf:"bytes,4,opt,name=policy_revision,json=policyRevision,proto3" json:"policy_revision,omitempty"` // copied out of policy as a convenience
	PolicyMetadata   string                 `protobuf:"bytes,5,opt,name=policy_metadata,json=policyMetadata,proto3" json:"policy_metadata,omitempty"` // copied out of policy as a convenience
	Policy           []byte                 `protobuf:"bytes,6,opt,name=policy,proto3" json:"policy,omitempty"`                                       // serialized policy
	Signature        []byte                 `protobuf:"bytes,7,opt,name=signature,proto3" json:"signature,omitempty"`                                 // signature of serialized policy
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PolicyContainer) Reset() {
	*x = PolicyContainer{}
	mi := &file_policy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyContainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyContainer) ProtoMessage() {}

func (x *PolicyContainer) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyContainer.ProtoReflect.Descriptor instead.
func (*PolicyContainer) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{0}
}

func (x *PolicyContainer) GetContainerVersion() uint32 {
	if x != nil {
		return x.ContainerVersion
	}
	return 0
}

func (x *PolicyContainer) GetPolicyDate() string {
	if x != nil {
		return x.PolicyDate
	}
	return ""
}

func (x *PolicyContainer) GetPolicyVersion() uint64 {
	if x != nil {
		return x.PolicyVersion
	}
	return 0
}

func (x *PolicyContainer) GetPolicyRevision() string {
	if x != nil {
		return x.PolicyRevision
	}
	return ""
}

func (x *PolicyContainer) GetPolicyMetadata() string {
	if x != nil {
		return x.PolicyMetadata
	}
	return ""
}

func (x *PolicyContainer) GetPolicy() []byte {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *PolicyContainer) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type Policy struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SerialVersion  uint32                 `protobuf:"varint,1,opt,name=serial_version,json=serialVersion,proto3" json:"serial_version,omitempty"`   // Increments when we alter this schema
	PolicyDate     string                 `protobuf:"bytes,2,opt,name=policy_date,json=policyDate,proto3" json:"policy_date,omitempty"`             // set in file or by compiler
	PolicyVersion  uint64                 `protobuf:"varint,3,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`   // set in file or by compiler arg (defaults to a timestamp)
	PolicyRevision string                 `protobuf:"bytes,4,opt,name=policy_revision,json=policyRevision,proto3" json:"policy_revision,omitempty"` // set in file or by compiler arg (but is required)
	PolicyMetadata string                 `protobuf:"bytes,5,opt,name=policy_metadata,json=policyMetadata,proto3" json:"policy_metadata,omitempty"`
	Connects       []*Connect             `protobuf:"bytes,6,rep,name=connects,proto3" json:"connects,omitempty"`
	Policies       []*CPolicy             `protobuf:"bytes,7,rep,name=policies,proto3" json:"policies,omitempty"`
	Services       []*Service             `protobuf:"bytes,8,rep,name=services,proto3" json:"services,omitempty"` // auth services (excludes "internal" cert-type auth services for some reason)
	Procs          []*Proc                `protobuf:"bytes,9,rep,name=procs,proto3" json:"procs,omitempty"`       // list of procedures, indexed by ID
	Links          []*Link                `protobuf:"bytes,10,rep,name=links,proto3" json:"links,omitempty"`
	Certificates   []*Cert                `protobuf:"bytes,11,rep,name=certificates,proto3" json:"certificates,omitempty"`                       // For datasources, including "internal".
	AttrKeyIndex   []string               `protobuf:"bytes,12,rep,name=attr_key_index,json=attrKeyIndex,proto3" json:"attr_key_index,omitempty"` // Attribute keys, in order
	AttrValIndex   []string               `protobuf:"bytes,13,rep,name=attr_val_index,json=attrValIndex,proto3" json:"attr_val_index,omitempty"` // Attribute values, in order
	Config         []*ConfigSetting       `protobuf:"bytes,14,rep,name=config,proto3" json:"config,omitempty"`                                   // Global settings
	Pubkeys        []*PublicKey           `protobuf:"bytes,15,rep,name=pubkeys,proto3" json:"pubkeys,omitempty"`                                 // Public keys used for bootstrap
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Policy) Reset() {
	*x = Policy{}
	mi := &file_policy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Policy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Policy) ProtoMessage() {}

func (x *Policy) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Policy.ProtoReflect.Descriptor instead.
func (*Policy) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{1}
}

func (x *Policy) GetSerialVersion() uint32 {
	if x != nil {
		return x.SerialVersion
	}
	return 0
}

func (x *Policy) GetPolicyDate() string {
	if x != nil {
		return x.PolicyDate
	}
	return ""
}

func (x *Policy) GetPolicyVersion() uint64 {
	if x != nil {
		return x.PolicyVersion
	}
	return 0
}

func (x *Policy) GetPolicyRevision() string {
	if x != nil {
		return x.PolicyRevision
	}
	return ""
}

func (x *Policy) GetPolicyMetadata() string {
	if x != nil {
		return x.PolicyMetadata
	}
	return ""
}

func (x *Policy) GetConnects() []*Connect {
	if x != nil {
		return x.Connects
	}
	return nil
}

func (x *Policy) GetPolicies() []*CPolicy {
	if x != nil {
		return x.Policies
	}
	return nil
}

func (x *Policy) GetServices() []*Service {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *Policy) GetProcs() []*Proc {
	if x != nil {
		return x.Procs
	}
	return nil
}

func (x *Policy) GetLinks() []*Link {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *Policy) GetCertificates() []*Cert {
	if x != nil {
		return x.Certificates
	}
	return nil
}

func (x *Policy) GetAttrKeyIndex() []string {
	if x != nil {
		return x.AttrKeyIndex
	}
	return nil
}

func (x *Policy) GetAttrValIndex() []string {
	if x != nil {
		return x.AttrValIndex
	}
	return nil
}

func (x *Policy) GetConfig() []*ConfigSetting {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *Policy) GetPubkeys() []*PublicKey {
	if x != nil {
		return x.Pubkeys
	}
	return nil
}

// Configuration settings (usually embodiment specific)
type ConfigSetting struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Key   uint32                 `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"` // keys < 1024 reserved for ZPR
	// Types that are valid to be assigned to Val:
	//
	//	*ConfigSetting_Sv
	//	*ConfigSetting_U32V
	//	*ConfigSetting_U64V
	//	*ConfigSetting_Bv
	Val           isConfigSetting_Val `protobuf_oneof:"val"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigSetting) Reset() {
	*x = ConfigSetting{}
	mi := &file_policy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigSetting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigSetting) ProtoMessage() {}

func (x *ConfigSetting) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigSetting.ProtoReflect.Descriptor instead.
func (*ConfigSetting) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{2}
}

func (x *ConfigSetting) GetKey() uint32 {
	if x != nil {
		return x.Key
	}
	return 0
}

func (x *ConfigSetting) GetVal() isConfigSetting_Val {
	if x != nil {
		return x.Val
	}
	return nil
}

func (x *ConfigSetting) GetSv() string {
	if x != nil {
		if x, ok := x.Val.(*ConfigSetting_Sv); ok {
			return x.Sv
		}
	}
	return ""
}

func (x *ConfigSetting) GetU32V() uint32 {
	if x != nil {
		if x, ok := x.Val.(*ConfigSetting_U32V); ok {
			return x.U32V
		}
	}
	return 0
}

func (x *ConfigSetting) GetU64V() uint64 {
	if x != nil {
		if x, ok := x.Val.(*ConfigSetting_U64V); ok {
			return x.U64V
		}
	}
	return 0
}

func (x *ConfigSetting) GetBv() bool {
	if x != nil {
		if x, ok := x.Val.(*ConfigSetting_Bv); ok {
			return x.Bv
		}
	}
	return false
}

type isConfigSetting_Val interface {
	isConfigSetting_Val()
}

type ConfigSetting_Sv struct {
	Sv string `protobuf:"bytes,2,opt,name=sv,proto3,oneof"`
}

type ConfigSetting_U32V struct {
	U32V uint32 `protobuf:"varint,3,opt,name=u32v,proto3,oneof"`
}

type ConfigSetting_U64V struct {
	U64V uint64 `protobuf:"varint,4,opt,name=u64v,proto3,oneof"`
}

type ConfigSetting_Bv struct {
	Bv bool `protobuf:"varint,5,opt,name=bv,proto3,oneof"`
}

func (*ConfigSetting_Sv) isConfigSetting_Val() {}

func (*ConfigSetting_U32V) isConfigSetting_Val() {}

func (*ConfigSetting_U64V) isConfigSetting_Val() {}

func (*ConfigSetting_Bv) isConfigSetting_Val() {}

// Connect enforces connection policy
type Connect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttrExprs     []*AttrExpr            `protobuf:"bytes,1,rep,name=attrExprs,proto3" json:"attrExprs,omitempty"`
	Proc          uint32                 `protobuf:"varint,2,opt,name=proc,proto3" json:"proc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Connect) Reset() {
	*x = Connect{}
	mi := &file_policy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Connect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Connect) ProtoMessage() {}

func (x *Connect) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Connect.ProtoReflect.Descriptor instead.
func (*Connect) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{3}
}

func (x *Connect) GetAttrExprs() []*AttrExpr {
	if x != nil {
		return x.AttrExprs
	}
	return nil
}

func (x *Connect) GetProc() uint32 {
	if x != nil {
		return x.Proc
	}
	return 0
}

// CPolicy is a Communications Policy
type CPolicy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"` // required to match the service (which may get dynamic addr)
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Scope         []*Scope               `protobuf:"bytes,3,rep,name=scope,proto3" json:"scope,omitempty"`
	Conditions    []*Condition           `protobuf:"bytes,4,rep,name=conditions,proto3" json:"conditions,omitempty"`
	Constraints   []*Constraint          `protobuf:"bytes,5,rep,name=constraints,proto3" json:"constraints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CPolicy) Reset() {
	*x = CPolicy{}
	mi := &file_policy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CPolicy) ProtoMessage() {}

func (x *CPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CPolicy.ProtoReflect.Descriptor instead.
func (*CPolicy) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{4}
}

func (x *CPolicy) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *CPolicy) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CPolicy) GetScope() []*Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *CPolicy) GetConditions() []*Condition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *CPolicy) GetConstraints() []*Constraint {
	if x != nil {
		return x.Constraints
	}
	return nil
}

type Service struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          SvcT                   `protobuf:"varint,1,opt,name=type,proto3,enum=polio.SvcT" json:"type,omitempty"`                 // only "auth" is known at the moment.
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                  // service "provides" value
	Prefix        string                 `protobuf:"bytes,3,opt,name=prefix,proto3" json:"prefix,omitempty"`                              // datasource prefix
	Domain        string                 `protobuf:"bytes,4,opt,name=domain,proto3" json:"domain,omitempty"`                              // TLS domain
	QueryUri      string                 `protobuf:"bytes,5,opt,name=query_uri,json=queryUri,proto3" json:"query_uri,omitempty"`          // Empty, or needs an l7 protocol name and port.
	ValidateUri   string                 `protobuf:"bytes,6,opt,name=validate_uri,json=validateUri,proto3" json:"validate_uri,omitempty"` // Empty, or needs an l7 protocol name and port.
	Attrs         []string               `protobuf:"bytes,7,rep,name=attrs,proto3" json:"attrs,omitempty"`                                // Returns attribute keys (with domains)
	IdAttrs       []string               `protobuf:"bytes,8,rep,name=id_attrs,json=idAttrs,proto3" json:"id_attrs,omitempty"`             // Identity attribute keys (with domains)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Service) Reset() {
	*x = Service{}
	mi := &file_policy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{5}
}

func (x *Service) GetType() SvcT {
	if x != nil {
		return x.Type
	}
	return SvcT_SVCT_UNUSED
}

func (x *Service) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Service) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *Service) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Service) GetQueryUri() string {
	if x != nil {
		return x.QueryUri
	}
	return ""
}

func (x *Service) GetValidateUri() string {
	if x != nil {
		return x.ValidateUri
	}
	return ""
}

func (x *Service) GetAttrs() []string {
	if x != nil {
		return x.Attrs
	}
	return nil
}

func (x *Service) GetIdAttrs() []string {
	if x != nil {
		return x.IdAttrs
	}
	return nil
}

type Condition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AttrExprs     []*AttrExpr            `protobuf:"bytes,2,rep,name=attrExprs,proto3" json:"attrExprs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Condition) Reset() {
	*x = Condition{}
	mi := &file_policy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Condition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Condition) ProtoMessage() {}

func (x *Condition) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Condition.ProtoReflect.Descriptor instead.
func (*Condition) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{6}
}

func (x *Condition) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Condition) GetAttrExprs() []*AttrExpr {
	if x != nil {
		return x.AttrExprs
	}
	return nil
}

type Constraint struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Carg:
	//
	//	*Constraint_Bw
	//	*Constraint_Dur
	//	*Constraint_Cap
	Carg          isConstraint_Carg `protobuf_oneof:"carg"`
	Group         string            `protobuf:"bytes,4,opt,name=group,proto3" json:"group,omitempty"` // optional group tag
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Constraint) Reset() {
	*x = Constraint{}
	mi := &file_policy_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Constraint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Constraint) ProtoMessage() {}

func (x *Constraint) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Constraint.ProtoReflect.Descriptor instead.
func (*Constraint) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{7}
}

func (x *Constraint) GetCarg() isConstraint_Carg {
	if x != nil {
		return x.Carg
	}
	return nil
}

func (x *Constraint) GetBw() *BWConstraint {
	if x != nil {
		if x, ok := x.Carg.(*Constraint_Bw); ok {
			return x.Bw
		}
	}
	return nil
}

func (x *Constraint) GetDur() *DurConstraint {
	if x != nil {
		if x, ok := x.Carg.(*Constraint_Dur); ok {
			return x.Dur
		}
	}
	return nil
}

func (x *Constraint) GetCap() *DataCapConstraint {
	if x != nil {
		if x, ok := x.Carg.(*Constraint_Cap); ok {
			return x.Cap
		}
	}
	return nil
}

func (x *Constraint) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

type isConstraint_Carg interface {
	isConstraint_Carg()
}

type Constraint_Bw struct {
	Bw *BWConstraint `protobuf:"bytes,1,opt,name=bw,proto3,oneof"`
}

type Constraint_Dur struct {
	Dur *DurConstraint `protobuf:"bytes,2,opt,name=dur,proto3,oneof"`
}

type Constraint_Cap struct {
	Cap *DataCapConstraint `protobuf:"bytes,3,opt,name=cap,proto3,oneof"`
}

func (*Constraint_Bw) isConstraint_Carg() {}

func (*Constraint_Dur) isConstraint_Carg() {}

func (*Constraint_Cap) isConstraint_Carg() {}

type BWConstraint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BitsPerSec    uint64                 `protobuf:"varint,1,opt,name=bits_per_sec,json=bitsPerSec,proto3" json:"bits_per_sec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BWConstraint) Reset() {
	*x = BWConstraint{}
	mi := &file_policy_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BWConstraint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BWConstraint) ProtoMessage() {}

func (x *BWConstraint) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BWConstraint.ProtoReflect.Descriptor instead.
func (*BWConstraint) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{8}
}

func (x *BWConstraint) GetBitsPerSec() uint64 {
	if x != nil {
		return x.BitsPerSec
	}
	return 0
}

type DurConstraint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seconds       uint64                 `protobuf:"varint,1,opt,name=seconds,proto3" json:"seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DurConstraint) Reset() {
	*x = DurConstraint{}
	mi := &file_policy_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DurConstraint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DurConstraint) ProtoMessage() {}

func (x *DurConstraint) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DurConstraint.ProtoReflect.Descriptor instead.
func (*DurConstraint) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{9}
}

func (x *DurConstraint) GetSeconds() uint64 {
	if x != nil {
		return x.Seconds
	}
	return 0
}

type DataCapConstraint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CapBytes      uint64                 `protobuf:"varint,1,opt,name=cap_bytes,json=capBytes,proto3" json:"cap_bytes,omitempty"`                // This much data
	PeriodSeconds uint64                 `protobuf:"varint,2,opt,name=period_seconds,json=periodSeconds,proto3" json:"period_seconds,omitempty"` // Over this period (in seconds)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataCapConstraint) Reset() {
	*x = DataCapConstraint{}
	mi := &file_policy_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataCapConstraint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataCapConstraint) ProtoMessage() {}

func (x *DataCapConstraint) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataCapConstraint.ProtoReflect.Descriptor instead.
func (*DataCapConstraint) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{10}
}

func (x *DataCapConstraint) GetCapBytes() uint64 {
	if x != nil {
		return x.CapBytes
	}
	return 0
}

func (x *DataCapConstraint) GetPeriodSeconds() uint64 {
	if x != nil {
		return x.PeriodSeconds
	}
	return 0
}

type Scope struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Protocol uint32                 `protobuf:"varint,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	// Types that are valid to be assigned to Protarg:
	//
	//	*Scope_Pspec
	//	*Scope_Icmp
	Protarg       isScope_Protarg `protobuf_oneof:"protarg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Scope) Reset() {
	*x = Scope{}
	mi := &file_policy_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scope) ProtoMessage() {}

func (x *Scope) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scope.ProtoReflect.Descriptor instead.
func (*Scope) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{11}
}

func (x *Scope) GetProtocol() uint32 {
	if x != nil {
		return x.Protocol
	}
	return 0
}

func (x *Scope) GetProtarg() isScope_Protarg {
	if x != nil {
		return x.Protarg
	}
	return nil
}

func (x *Scope) GetPspec() *PortSpecList {
	if x != nil {
		if x, ok := x.Protarg.(*Scope_Pspec); ok {
			return x.Pspec
		}
	}
	return nil
}

func (x *Scope) GetIcmp() *ICMP {
	if x != nil {
		if x, ok := x.Protarg.(*Scope_Icmp); ok {
			return x.Icmp
		}
	}
	return nil
}

type isScope_Protarg interface {
	isScope_Protarg()
}

type Scope_Pspec struct {
	Pspec *PortSpecList `protobuf:"bytes,2,opt,name=pspec,proto3,oneof"`
}

type Scope_Icmp struct {
	Icmp *ICMP `protobuf:"bytes,3,opt,name=icmp,proto3,oneof"`
}

func (*Scope_Pspec) isScope_Protarg() {}

func (*Scope_Icmp) isScope_Protarg() {}

// ICMP is either a single TYPECODE or a pair for request-response.
// In that case, the response type is only allowed after a request.
type ICMP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ICMPT                  `protobuf:"varint,1,opt,name=type,proto3,enum=polio.ICMPT" json:"type,omitempty"`
	Codes         []uint32               `protobuf:"varint,2,rep,packed,name=codes,proto3" json:"codes,omitempty"` // single code, or REQUEST_CODE, RESPONSE_CODE.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ICMP) Reset() {
	*x = ICMP{}
	mi := &file_policy_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ICMP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ICMP) ProtoMessage() {}

func (x *ICMP) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ICMP.ProtoReflect.Descriptor instead.
func (*ICMP) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{12}
}

func (x *ICMP) GetType() ICMPT {
	if x != nil {
		return x.Type
	}
	return ICMPT_ICMPT_UNUSED
}

func (x *ICMP) GetCodes() []uint32 {
	if x != nil {
		return x.Codes
	}
	return nil
}

type PortSpecList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spec          []*PortSpec            `protobuf:"bytes,1,rep,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortSpecList) Reset() {
	*x = PortSpecList{}
	mi := &file_policy_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortSpecList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortSpecList) ProtoMessage() {}

func (x *PortSpecList) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortSpecList.ProtoReflect.Descriptor instead.
func (*PortSpecList) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{13}
}

func (x *PortSpecList) GetSpec() []*PortSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type PortSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Parg:
	//
	//	*PortSpec_Port
	//	*PortSpec_Pr
	Parg          isPortSpec_Parg `protobuf_oneof:"parg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortSpec) Reset() {
	*x = PortSpec{}
	mi := &file_policy_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortSpec) ProtoMessage() {}

func (x *PortSpec) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortSpec.ProtoReflect.Descriptor instead.
func (*PortSpec) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{14}
}

func (x *PortSpec) GetParg() isPortSpec_Parg {
	if x != nil {
		return x.Parg
	}
	return nil
}

func (x *PortSpec) GetPort() uint32 {
	if x != nil {
		if x, ok := x.Parg.(*PortSpec_Port); ok {
			return x.Port
		}
	}
	return 0
}

func (x *PortSpec) GetPr() *PortRange {
	if x != nil {
		if x, ok := x.Parg.(*PortSpec_Pr); ok {
			return x.Pr
		}
	}
	return nil
}

type isPortSpec_Parg interface {
	isPortSpec_Parg()
}

type PortSpec_Port struct {
	Port uint32 `protobuf:"varint,1,opt,name=port,proto3,oneof"`
}

type PortSpec_Pr struct {
	Pr *PortRange `protobuf:"bytes,2,opt,name=pr,proto3,oneof"`
}

func (*PortSpec_Port) isPortSpec_Parg() {}

func (*PortSpec_Pr) isPortSpec_Parg() {}

type PortRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Low           uint32                 `protobuf:"varint,1,opt,name=low,proto3" json:"low,omitempty"`
	High          uint32                 `protobuf:"varint,2,opt,name=high,proto3" json:"high,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortRange) Reset() {
	*x = PortRange{}
	mi := &file_policy_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortRange) ProtoMessage() {}

func (x *PortRange) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortRange.ProtoReflect.Descriptor instead.
func (*PortRange) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{15}
}

func (x *PortRange) GetLow() uint32 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *PortRange) GetHigh() uint32 {
	if x != nil {
		return x.High
	}
	return 0
}

type AttrExpr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           uint32                 `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	Op            AttrOpT                `protobuf:"varint,2,opt,name=op,proto3,enum=polio.AttrOpT" json:"op,omitempty"`
	Val           uint32                 `protobuf:"varint,3,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttrExpr) Reset() {
	*x = AttrExpr{}
	mi := &file_policy_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttrExpr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttrExpr) ProtoMessage() {}

func (x *AttrExpr) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttrExpr.ProtoReflect.Descriptor instead.
func (*AttrExpr) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{16}
}

func (x *AttrExpr) GetKey() uint32 {
	if x != nil {
		return x.Key
	}
	return 0
}

func (x *AttrExpr) GetOp() AttrOpT {
	if x != nil {
		return x.Op
	}
	return AttrOpT_UNUSED
}

func (x *AttrExpr) GetVal() uint32 {
	if x != nil {
		return x.Val
	}
	return 0
}

type Cert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            uint32                 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`            // TODO: What is this?
	Asn1Data      []byte                 `protobuf:"bytes,2,opt,name=asn1data,proto3" json:"asn1data,omitempty"` // DER encoded x509
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`         // = auth "prefix"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cert) Reset() {
	*x = Cert{}
	mi := &file_policy_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cert) ProtoMessage() {}

func (x *Cert) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cert.ProtoReflect.Descriptor instead.
func (*Cert) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{17}
}

func (x *Cert) GetID() uint32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Cert) GetAsn1Data() []byte {
	if x != nil {
		return x.Asn1Data
	}
	return nil
}

func (x *Cert) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type PublicKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cn            string                 `protobuf:"bytes,1,opt,name=cn,proto3" json:"cn,omitempty"`
	Keydata       []byte                 `protobuf:"bytes,2,opt,name=keydata,proto3" json:"keydata,omitempty"` // DER encoded x509
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicKey) Reset() {
	*x = PublicKey{}
	mi := &file_policy_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicKey) ProtoMessage() {}

func (x *PublicKey) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicKey.ProtoReflect.Descriptor instead.
func (*PublicKey) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{18}
}

func (x *PublicKey) GetCn() string {
	if x != nil {
		return x.Cn
	}
	return ""
}

func (x *PublicKey) GetKeydata() []byte {
	if x != nil {
		return x.Keydata
	}
	return nil
}

type Proc struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Proc          []*Instruction         `protobuf:"bytes,1,rep,name=proc,proto3" json:"proc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Proc) Reset() {
	*x = Proc{}
	mi := &file_policy_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Proc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Proc) ProtoMessage() {}

func (x *Proc) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Proc.ProtoReflect.Descriptor instead.
func (*Proc) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{19}
}

func (x *Proc) GetProc() []*Instruction {
	if x != nil {
		return x.Proc
	}
	return nil
}

type Instruction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Opcode        OpCodeT                `protobuf:"varint,1,opt,name=opcode,proto3,enum=polio.OpCodeT" json:"opcode,omitempty"`
	Args          []*Argument            `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Instruction) Reset() {
	*x = Instruction{}
	mi := &file_policy_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Instruction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instruction) ProtoMessage() {}

func (x *Instruction) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Instruction.ProtoReflect.Descriptor instead.
func (*Instruction) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{20}
}

func (x *Instruction) GetOpcode() OpCodeT {
	if x != nil {
		return x.Opcode
	}
	return OpCodeT_OP_Nop
}

func (x *Instruction) GetArgs() []*Argument {
	if x != nil {
		return x.Args
	}
	return nil
}

type StringPair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             string                 `protobuf:"bytes,1,opt,name=a,proto3" json:"a,omitempty"`
	B             string                 `protobuf:"bytes,2,opt,name=b,proto3" json:"b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringPair) Reset() {
	*x = StringPair{}
	mi := &file_policy_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringPair) ProtoMessage() {}

func (x *StringPair) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringPair.ProtoReflect.Descriptor instead.
func (*StringPair) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{21}
}

func (x *StringPair) GetA() string {
	if x != nil {
		return x.A
	}
	return ""
}

func (x *StringPair) GetB() string {
	if x != nil {
		return x.B
	}
	return ""
}

type Argument struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Arg:
	//
	//	*Argument_Ival
	//	*Argument_Uival
	//	*Argument_Strval
	//	*Argument_Bval
	//	*Argument_Flagval
	//	*Argument_Svcval
	//	*Argument_Insval
	//	*Argument_Spval
	Arg           isArgument_Arg `protobuf_oneof:"arg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Argument) Reset() {
	*x = Argument{}
	mi := &file_policy_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Argument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Argument) ProtoMessage() {}

func (x *Argument) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Argument.ProtoReflect.Descriptor instead.
func (*Argument) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{22}
}

func (x *Argument) GetArg() isArgument_Arg {
	if x != nil {
		return x.Arg
	}
	return nil
}

func (x *Argument) GetIval() int64 {
	if x != nil {
		if x, ok := x.Arg.(*Argument_Ival); ok {
			return x.Ival
		}
	}
	return 0
}

func (x *Argument) GetUival() uint64 {
	if x != nil {
		if x, ok := x.Arg.(*Argument_Uival); ok {
			return x.Uival
		}
	}
	return 0
}

func (x *Argument) GetStrval() string {
	if x != nil {
		if x, ok := x.Arg.(*Argument_Strval); ok {
			return x.Strval
		}
	}
	return ""
}

func (x *Argument) GetBval() bool {
	if x != nil {
		if x, ok := x.Arg.(*Argument_Bval); ok {
			return x.Bval
		}
	}
	return false
}

func (x *Argument) GetFlagval() FlagT {
	if x != nil {
		if x, ok := x.Arg.(*Argument_Flagval); ok {
			return x.Flagval
		}
	}
	return FlagT_F_UNUSED
}

func (x *Argument) GetSvcval() SvcT {
	if x != nil {
		if x, ok := x.Arg.(*Argument_Svcval); ok {
			return x.Svcval
		}
	}
	return SvcT_SVCT_UNUSED
}

func (x *Argument) GetInsval() *Instruction {
	if x != nil {
		if x, ok := x.Arg.(*Argument_Insval); ok {
			return x.Insval
		}
	}
	return nil
}

func (x *Argument) GetSpval() *StringPair {
	if x != nil {
		if x, ok := x.Arg.(*Argument_Spval); ok {
			return x.Spval
		}
	}
	return nil
}

type isArgument_Arg interface {
	isArgument_Arg()
}

type Argument_Ival struct {
	Ival int64 `protobuf:"varint,1,opt,name=ival,proto3,oneof"`
}

type Argument_Uival struct {
	Uival uint64 `protobuf:"varint,2,opt,name=uival,proto3,oneof"`
}

type Argument_Strval struct {
	Strval string `protobuf:"bytes,3,opt,name=strval,proto3,oneof"`
}

type Argument_Bval struct {
	Bval bool `protobuf:"varint,4,opt,name=bval,proto3,oneof"`
}

type Argument_Flagval struct {
	Flagval FlagT `protobuf:"varint,5,opt,name=flagval,proto3,enum=polio.FlagT,oneof"`
}

type Argument_Svcval struct {
	Svcval SvcT `protobuf:"varint,6,opt,name=svcval,proto3,enum=polio.SvcT,oneof"`
}

type Argument_Insval struct {
	Insval *Instruction `protobuf:"bytes,7,opt,name=insval,proto3,oneof"`
}

type Argument_Spval struct {
	Spval *StringPair `protobuf:"bytes,8,opt,name=spval,proto3,oneof"`
}

func (*Argument_Ival) isArgument_Arg() {}

func (*Argument_Uival) isArgument_Arg() {}

func (*Argument_Strval) isArgument_Arg() {}

func (*Argument_Bval) isArgument_Arg() {}

func (*Argument_Flagval) isArgument_Arg() {}

func (*Argument_Svcval) isArgument_Arg() {}

func (*Argument_Insval) isArgument_Arg() {}

func (*Argument_Spval) isArgument_Arg() {}

// NodeAddr is the end of a link
type NodeAddr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ZprId         []byte                 `protobuf:"bytes,1,opt,name=zpr_id,json=zprId,proto3" json:"zpr_id,omitempty"`
	Host          string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`                       // IP or Hostname
	Port          uint32                 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`                      // for node-node IPv4 connection
	ExtAuth       bool                   `protobuf:"varint,4,opt,name=ext_auth,json=extAuth,proto3" json:"ext_auth,omitempty"` // true if node requires auth service
	Cost          uint32                 `protobuf:"varint,5,opt,name=cost,proto3" json:"cost,omitempty"`                      // link cost
	Key           []byte                 `protobuf:"bytes,6,opt,name=key,proto3" json:"key,omitempty"`                         // Noise PK (32 bytes)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeAddr) Reset() {
	*x = NodeAddr{}
	mi := &file_policy_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeAddr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeAddr) ProtoMessage() {}

func (x *NodeAddr) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeAddr.ProtoReflect.Descriptor instead.
func (*NodeAddr) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{23}
}

func (x *NodeAddr) GetZprId() []byte {
	if x != nil {
		return x.ZprId
	}
	return nil
}

func (x *NodeAddr) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *NodeAddr) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *NodeAddr) GetExtAuth() bool {
	if x != nil {
		return x.ExtAuth
	}
	return false
}

func (x *NodeAddr) GetCost() uint32 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *NodeAddr) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type Link struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceId      []byte                 `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"` // zpr id value for link originator
	Terms         []*NodeAddr            `protobuf:"bytes,2,rep,name=terms,proto3" json:"terms,omitempty"`                       // link terminators
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Link) Reset() {
	*x = Link{}
	mi := &file_policy_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Link) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Link) ProtoMessage() {}

func (x *Link) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Link.ProtoReflect.Descriptor instead.
func (*Link) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{24}
}

func (x *Link) GetSourceId() []byte {
	if x != nil {
		return x.SourceId
	}
	return nil
}

func (x *Link) GetTerms() []*NodeAddr {
	if x != nil {
		return x.Terms
	}
	return nil
}

var File_policy_proto protoreflect.FileDescriptor

const file_policy_proto_rawDesc = "" +
	"\n" +
	"\fpolicy.proto\x12\x05polio\"\x8e\x02\n" +
	"\x0fPolicyContainer\x12+\n" +
	"\x11container_version\x18\x01 \x01(\rR\x10containerVersion\x12\x1f\n" +
	"\vpolicy_date\x18\x02 \x01(\tR\n" +
	"policyDate\x12%\n" +
	"\x0epolicy_version\x18\x03 \x01(\x04R\rpolicyVersion\x12'\n" +
	"\x0fpolicy_revision\x18\x04 \x01(\tR\x0epolicyRevision\x12'\n" +
	"\x0fpolicy_metadata\x18\x05 \x01(\tR\x0epolicyMetadata\x12\x16\n" +
	"\x06policy\x18\x06 \x01(\fR\x06policy\x12\x1c\n" +
	"\tsignature\x18\a \x01(\fR\tsignature\"\xea\x04\n" +
	"\x06Policy\x12%\n" +
	"\x0eserial_version\x18\x01 \x01(\rR\rserialVersion\x12\x1f\n" +
	"\vpolicy_date\x18\x02 \x01(\tR\n" +
	"policyDate\x12%\n" +
	"\x0epolicy_version\x18\x03 \x01(\x04R\rpolicyVersion\x12'\n" +
	"\x0fpolicy_revision\x18\x04 \x01(\tR\x0epolicyRevision\x12'\n" +
	"\x0fpolicy_metadata\x18\x05 \x01(\tR\x0epolicyMetadata\x12*\n" +
	"\bconnects\x18\x06 \x03(\v2\x0e.polio.ConnectR\bconnects\x12*\n" +
	"\bpolicies\x18\a \x03(\v2\x0e.polio.CPolicyR\bpolicies\x12*\n" +
	"\bservices\x18\b \x03(\v2\x0e.polio.ServiceR\bservices\x12!\n" +
	"\x05procs\x18\t \x03(\v2\v.polio.ProcR\x05procs\x12!\n" +
	"\x05links\x18\n" +
	" \x03(\v2\v.polio.LinkR\x05links\x12/\n" +
	"\fcertificates\x18\v \x03(\v2\v.polio.CertR\fcertificates\x12$\n" +
	"\x0eattr_key_index\x18\f \x03(\tR\fattrKeyIndex\x12$\n" +
	"\x0eattr_val_index\x18\r \x03(\tR\fattrValIndex\x12,\n" +
	"\x06config\x18\x0e \x03(\v2\x14.polio.ConfigSettingR\x06config\x12*\n" +
	"\apubkeys\x18\x0f \x03(\v2\x10.polio.PublicKeyR\apubkeys\"x\n" +
	"\rConfigSetting\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12\x10\n" +
	"\x02sv\x18\x02 \x01(\tH\x00R\x02sv\x12\x14\n" +
	"\x04u32v\x18\x03 \x01(\rH\x00R\x04u32v\x12\x14\n" +
	"\x04u64v\x18\x04 \x01(\x04H\x00R\x04u64v\x12\x10\n" +
	"\x02bv\x18\x05 \x01(\bH\x00R\x02bvB\x05\n" +
	"\x03val\"L\n" +
	"\aConnect\x12-\n" +
	"\tattrExprs\x18\x01 \x03(\v2\x0f.polio.AttrExprR\tattrExprs\x12\x12\n" +
	"\x04proc\x18\x02 \x01(\rR\x04proc\"\xc3\x01\n" +
	"\aCPolicy\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\"\n" +
	"\x05scope\x18\x03 \x03(\v2\f.polio.ScopeR\x05scope\x120\n" +
	"\n" +
	"conditions\x18\x04 \x03(\v2\x10.polio.ConditionR\n" +
	"conditions\x123\n" +
	"\vconstraints\x18\x05 \x03(\v2\x11.polio.ConstraintR\vconstraints\"\xdf\x01\n" +
	"\aService\x12\x1f\n" +
	"\x04type\x18\x01 \x01(\x0e2\v.polio.SvcTR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06prefix\x18\x03 \x01(\tR\x06prefix\x12\x16\n" +
	"\x06domain\x18\x04 \x01(\tR\x06domain\x12\x1b\n" +
	"\tquery_uri\x18\x05 \x01(\tR\bqueryUri\x12!\n" +
	"\fvalidate_uri\x18\x06 \x01(\tR\vvalidateUri\x12\x14\n" +
	"\x05attrs\x18\a \x03(\tR\x05attrs\x12\x19\n" +
	"\bid_attrs\x18\b \x03(\tR\aidAttrs\"J\n" +
	"\tCondition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12-\n" +
	"\tattrExprs\x18\x02 \x03(\v2\x0f.polio.AttrExprR\tattrExprs\"\xa9\x01\n" +
	"\n" +
	"Constraint\x12%\n" +
	"\x02bw\x18\x01 \x01(\v2\x13.polio.BWConstraintH\x00R\x02bw\x12(\n" +
	"\x03dur\x18\x02 \x01(\v2\x14.polio.DurConstraintH\x00R\x03dur\x12,\n" +
	"\x03cap\x18\x03 \x01(\v2\x18.polio.DataCapConstraintH\x00R\x03cap\x12\x14\n" +
	"\x05group\x18\x04 \x01(\tR\x05groupB\x06\n" +
	"\x04carg\"0\n" +
	"\fBWConstraint\x12 \n" +
	"\fbits_per_sec\x18\x01 \x01(\x04R\n" +
	"bitsPerSec\")\n" +
	"\rDurConstraint\x12\x18\n" +
	"\aseconds\x18\x01 \x01(\x04R\aseconds\"W\n" +
	"\x11DataCapConstraint\x12\x1b\n" +
	"\tcap_bytes\x18\x01 \x01(\x04R\bcapBytes\x12%\n" +
	"\x0eperiod_seconds\x18\x02 \x01(\x04R\rperiodSeconds\"~\n" +
	"\x05Scope\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\rR\bprotocol\x12+\n" +
	"\x05pspec\x18\x02 \x01(\v2\x13.polio.PortSpecListH\x00R\x05pspec\x12!\n" +
	"\x04icmp\x18\x03 \x01(\v2\v.polio.ICMPH\x00R\x04icmpB\t\n" +
	"\aprotarg\">\n" +
	"\x04ICMP\x12 \n" +
	"\x04type\x18\x01 \x01(\x0e2\f.polio.ICMPTR\x04type\x12\x14\n" +
	"\x05codes\x18\x02 \x03(\rR\x05codes\"3\n" +
	"\fPortSpecList\x12#\n" +
	"\x04spec\x18\x01 \x03(\v2\x0f.polio.PortSpecR\x04spec\"L\n" +
	"\bPortSpec\x12\x14\n" +
	"\x04port\x18\x01 \x01(\rH\x00R\x04port\x12\"\n" +
	"\x02pr\x18\x02 \x01(\v2\x10.polio.PortRangeH\x00R\x02prB\x06\n" +
	"\x04parg\"1\n" +
	"\tPortRange\x12\x10\n" +
	"\x03low\x18\x01 \x01(\rR\x03low\x12\x12\n" +
	"\x04high\x18\x02 \x01(\rR\x04high\"N\n" +
	"\bAttrExpr\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12\x1e\n" +
	"\x02op\x18\x02 \x01(\x0e2\x0e.polio.AttrOpTR\x02op\x12\x10\n" +
	"\x03val\x18\x03 \x01(\rR\x03val\"F\n" +
	"\x04Cert\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\rR\x02ID\x12\x1a\n" +
	"\basn1data\x18\x02 \x01(\fR\basn1data\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"5\n" +
	"\tPublicKey\x12\x0e\n" +
	"\x02cn\x18\x01 \x01(\tR\x02cn\x12\x18\n" +
	"\akeydata\x18\x02 \x01(\fR\akeydata\".\n" +
	"\x04Proc\x12&\n" +
	"\x04proc\x18\x01 \x03(\v2\x12.polio.InstructionR\x04proc\"Z\n" +
	"\vInstruction\x12&\n" +
	"\x06opcode\x18\x01 \x01(\x0e2\x0e.polio.OpCodeTR\x06opcode\x12#\n" +
	"\x04args\x18\x02 \x03(\v2\x0f.polio.ArgumentR\x04args\"(\n" +
	"\n" +
	"StringPair\x12\f\n" +
	"\x01a\x18\x01 \x01(\tR\x01a\x12\f\n" +
	"\x01b\x18\x02 \x01(\tR\x01b\"\x99\x02\n" +
	"\bArgument\x12\x14\n" +
	"\x04ival\x18\x01 \x01(\x03H\x00R\x04ival\x12\x16\n" +
	"\x05uival\x18\x02 \x01(\x04H\x00R\x05uival\x12\x18\n" +
	"\x06strval\x18\x03 \x01(\tH\x00R\x06strval\x12\x14\n" +
	"\x04bval\x18\x04 \x01(\bH\x00R\x04bval\x12(\n" +
	"\aflagval\x18\x05 \x01(\x0e2\f.polio.FlagTH\x00R\aflagval\x12%\n" +
	"\x06svcval\x18\x06 \x01(\x0e2\v.polio.SvcTH\x00R\x06svcval\x12,\n" +
	"\x06insval\x18\a \x01(\v2\x12.polio.InstructionH\x00R\x06insval\x12)\n" +
	"\x05spval\x18\b \x01(\v2\x11.polio.StringPairH\x00R\x05spvalB\x05\n" +
	"\x03arg\"\x8a\x01\n" +
	"\bNodeAddr\x12\x15\n" +
	"\x06zpr_id\x18\x01 \x01(\fR\x05zprId\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x03 \x01(\rR\x04port\x12\x19\n" +
	"\bext_auth\x18\x04 \x01(\bR\aextAuth\x12\x12\n" +
	"\x04cost\x18\x05 \x01(\rR\x04cost\x12\x10\n" +
	"\x03key\x18\x06 \x01(\fR\x03key\"J\n" +
	"\x04Link\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\fR\bsourceId\x12%\n" +
	"\x05terms\x18\x02 \x03(\v2\x0f.polio.NodeAddrR\x05terms*]\n" +
	"\x04SvcT\x12\x0f\n" +
	"\vSVCT_UNUSED\x10\x00\x12\f\n" +
	"\bSVCT_DEF\x10\x01\x12\r\n" +
	"\tSVCT_AUTH\x10\x02\x12\x12\n" +
	"\x0eSVCT_DECORATOR\x10\x03\x12\x13\n" +
	"\x0fSVCT_ACTOR_AUTH\x10\x04*;\n" +
	"\x05ICMPT\x12\x10\n" +
	"\fICMPT_UNUSED\x10\x00\x12\x10\n" +
	"\fICMPT_REQREP\x10\x01\x12\x0e\n" +
	"\n" +
	"ICMPT_ONCE\x10\x02*<\n" +
	"\aAttrOpT\x12\n" +
	"\n" +
	"\x06UNUSED\x10\x00\x12\x06\n" +
	"\x02EQ\x10\x01\x12\x06\n" +
	"\x02NE\x10\x02\x12\a\n" +
	"\x03HAS\x10\a\x12\f\n" +
	"\bEXCLUDES\x10\b*E\n" +
	"\aOpCodeT\x12\n" +
	"\n" +
	"\x06OP_Nop\x10\x00\x12\x0f\n" +
	"\vOP_Register\x10\x01\x12\x0e\n" +
	"\n" +
	"OP_SetFlag\x10\x02\x12\r\n" +
	"\tOP_SetCfg\x10\x03*C\n" +
	"\x05FlagT\x12\f\n" +
	"\bF_UNUSED\x10\x00\x12\n" +
	"\n" +
	"\x06F_NODE\x10\x01\x12\x11\n" +
	"\rF_VISASERVICE\x10\x02\x12\r\n" +
	"\tF_VS_DOCK\x10\x03B#Z!spacelaser.net/zpr/pkg/snet/poliob\x06proto3"

var (
	file_policy_proto_rawDescOnce sync.Once
	file_policy_proto_rawDescData []byte
)

func file_policy_proto_rawDescGZIP() []byte {
	file_policy_proto_rawDescOnce.Do(func() {
		file_policy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_policy_proto_rawDesc), len(file_policy_proto_rawDesc)))
	})
	return file_policy_proto_rawDescData
}

var file_policy_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_policy_proto_goTypes = []any{
	(SvcT)(0),                 // 0: polio.SvcT
	(ICMPT)(0),                // 1: polio.ICMPT
	(AttrOpT)(0),              // 2: polio.AttrOpT
	(OpCodeT)(0),              // 3: polio.OpCodeT
	(FlagT)(0),                // 4: polio.FlagT
	(*PolicyContainer)(nil),   // 5: polio.PolicyContainer
	(*Policy)(nil),            // 6: polio.Policy
	(*ConfigSetting)(nil),     // 7: polio.ConfigSetting
	(*Connect)(nil),           // 8: polio.Connect
	(*CPolicy)(nil),           // 9: polio.CPolicy
	(*Service)(nil),           // 10: polio.Service
	(*Condition)(nil),         // 11: polio.Condition
	(*Constraint)(nil),        // 12: polio.Constraint
	(*BWConstraint)(nil),      // 13: polio.BWConstraint
	(*DurConstraint)(nil),     // 14: polio.DurConstraint
	(*DataCapConstraint)(nil), // 15: polio.DataCapConstraint
	(*Scope)(nil),             // 16: polio.Scope
	(*ICMP)(nil),              // 17: polio.ICMP
	(*PortSpecList)(nil),      // 18: polio.PortSpecList
	(*PortSpec)(nil),          // 19: polio.PortSpec
	(*PortRange)(nil),         // 20: polio.PortRange
	(*AttrExpr)(nil),          // 21: polio.AttrExpr
	(*Cert)(nil),              // 22: polio.Cert
	(*PublicKey)(nil),         // 23: polio.PublicKey
	(*Proc)(nil),              // 24: polio.Proc
	(*Instruction)(nil),       // 25: polio.Instruction
	(*StringPair)(nil),        // 26: polio.StringPair
	(*Argument)(nil),          // 27: polio.Argument
	(*NodeAddr)(nil),          // 28: polio.NodeAddr
	(*Link)(nil),              // 29: polio.Link
}
var file_policy_proto_depIdxs = []int32{
	8,  // 0: polio.Policy.connects:type_name -> polio.Connect
	9,  // 1: polio.Policy.policies:type_name -> polio.CPolicy
	10, // 2: polio.Policy.services:type_name -> polio.Service
	24, // 3: polio.Policy.procs:type_name -> polio.Proc
	29, // 4: polio.Policy.links:type_name -> polio.Link
	22, // 5: polio.Policy.certificates:type_name -> polio.Cert
	7,  // 6: polio.Policy.config:type_name -> polio.ConfigSetting
	23, // 7: polio.Policy.pubkeys:type_name -> polio.PublicKey
	21, // 8: polio.Connect.attrExprs:type_name -> polio.AttrExpr
	16, // 9: polio.CPolicy.scope:type_name -> polio.Scope
	11, // 10: polio.CPolicy.conditions:type_name -> polio.Condition
	12, // 11: polio.CPolicy.constraints:type_name -> polio.Constraint
	0,  // 12: polio.Service.type:type_name -> polio.SvcT
	21, // 13: polio.Condition.attrExprs:type_name -> polio.AttrExpr
	13, // 14: polio.Constraint.bw:type_name -> polio.BWConstraint
	14, // 15: polio.Constraint.dur:type_name -> polio.DurConstraint
	15, // 16: polio.Constraint.cap:type_name -> polio.DataCapConstraint
	18, // 17: polio.Scope.pspec:type_name -> polio.PortSpecList
	17, // 18: polio.Scope.icmp:type_name -> polio.ICMP
	1,  // 19: polio.ICMP.type:type_name -> polio.ICMPT
	19, // 20: polio.PortSpecList.spec:type_name -> polio.PortSpec
	20, // 21: polio.PortSpec.pr:type_name -> polio.PortRange
	2,  // 22: polio.AttrExpr.op:type_name -> polio.AttrOpT
	25, // 23: polio.Proc.proc:type_name -> polio.Instruction
	3,  // 24: polio.Instruction.opcode:type_name -> polio.OpCodeT
	27, // 25: polio.Instruction.args:type_name -> polio.Argument
	4,  // 26: polio.Argument.flagval:type_name -> polio.FlagT
	0,  // 27: polio.Argument.svcval:type_name -> polio.SvcT
	25, // 28: polio.Argument.insval:type_name -> polio.Instruction
	26, // 29: polio.Argument.spval:type_name -> polio.StringPair
	28, // 30: polio.Link.terms:type_name -> polio.NodeAddr
	31, // [31:31] is the sub-list for method output_type
	31, // [31:31] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_policy_proto_init() }
func file_policy_proto_init() {
	if File_policy_proto != nil {
		return
	}
	file_policy_proto_msgTypes[2].OneofWrappers = []any{
		(*ConfigSetting_Sv)(nil),
		(*ConfigSetting_U32V)(nil),
		(*ConfigSetting_U64V)(nil),
		(*ConfigSetting_Bv)(nil),
	}
	file_policy_proto_msgTypes[7].OneofWrappers = []any{
		(*Constraint_Bw)(nil),
		(*Constraint_Dur)(nil),
		(*Constraint_Cap)(nil),
	}
	file_policy_proto_msgTypes[11].OneofWrappers = []any{
		(*Scope_Pspec)(nil),
		(*Scope_Icmp)(nil),
	}
	file_policy_proto_msgTypes[14].OneofWrappers = []any{
		(*PortSpec_Port)(nil),
		(*PortSpec_Pr)(nil),
	}
	file_policy_proto_msgTypes[22].OneofWrappers = []any{
		(*Argument_Ival)(nil),
		(*Argument_Uival)(nil),
		(*Argument_Strval)(nil),
		(*Argument_Bval)(nil),
		(*Argument_Flagval)(nil),
		(*Argument_Svcval)(nil),
		(*Argument_Insval)(nil),
		(*Argument_Spval)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_policy_proto_rawDesc), len(file_policy_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_policy_proto_goTypes,
		DependencyIndexes: file_policy_proto_depIdxs,
		EnumInfos:         file_policy_proto_enumTypes,
		MessageInfos:      file_policy_proto_msgTypes,
	}.Build()
	File_policy_proto = out.File
	file_policy_proto_goTypes = nil
	file_policy_proto_depIdxs = nil
}
