#!/usr/bin/env bash
set -euo pipefail

function usage() {
	cat <<EOF
Usage: $0 <command>

Tool for working with RFC 8410 compliant X.509 certificates containing
X25519 public keys as used in ZPR.

Available commands:

  genkey: Generate private key
  pubkey: Extract public key from private key
  toraw: Convert a PKCS #8-encoded X22519 key into raw Base64
  fromraw: Convert a raw Base64-encoded X22519 private key into PKCS #8
  fromrawpub: Convert a raw Base64-encoded X22519 public key into PKCS #8
  showkey: Pretty-print a private key
  showpubkey: Pretty-print only the public part of a private key
  gensignedcert: Generate a signed certificate for a private key
  showcert: Pretty-print a certificate
  showcertsubject: Print a certificate's subject
  showcertpubkey: Print a certificate's public key
  verifycert: Verify a certificate
  gencakey: Generate private key for a micro-CA
  gencacert: Generate a certificate for a micro-CA

Unless otherwise noted, all keys and certificates are in PEM format.

EOF
}

function cmd_usage() {
	cat <<EOF
Usage: $0 $CMD $*
EOF
}

if [[ $# < 1 ]]
then
	usage 1>&2
	exit 1
fi

CMD=$1
shift

function do_genkey() {
	if [[ $# > 0 ]]
	then cmd_usage "> privkey.pem" 1>&2; exit 1
	fi

	exec openssl genpkey -algorithm X25519
}

function do_pubkey() {
	if [[ $# > 0 ]]
	then cmd_usage "< privkey.pem > pubkey.pem" 1>&2; exit 1
	fi

	exec openssl pkey -pubout
}

function do_toraw() {
	if [[ $# > 0 ]]
	then cmd_usage "< key.pem > key.txt" 1>&2; exit 1
	fi

	exec openssl asn1parse -noout -out - | tail -c 32 | base64
}

function do_fromraw() {
	if [[ $# > 0 ]]
	then cmd_usage "< privkey.txt > privkey.pem" 1>&2; exit 1
	fi

	echo "-----BEGIN PRIVATE KEY-----"
	{ echo -en '\x30\x2e\x02\x01\x00\x30\x05\x06\x03\x2b\x65\x6e\x04\x22\x04\x20'; base64 -d; } | base64
	echo "-----END PRIVATE KEY-----"
}

function do_fromrawpub() {
	if [[ $# > 0 ]]
	then cmd_usage "< pubkey.txt > pubkey.pem" 1>&2; exit 1
	fi

	echo "-----BEGIN PUBLIC KEY-----"
	{ echo -en '\x30\x2a\x30\x05\x06\x03\x2b\x65\x6e\x03\x21\x00'; base64 -d; } | base64
	echo "-----END PUBLIC KEY-----"
}

function do_showkey() {
	if [[ $# > 0 ]]
	then cmd_usage "< privkey.pem" 1>&2; exit 1
	fi

	exec openssl pkey -text -noout
}

function do_showpubkey() {
	if [[ $# > 0 ]]
	then cmd_usage "< privkey.pem" 1>&2; exit 1
	fi

	exec openssl pkey -text_pub -noout
}

function do_gensignedcert() {
	if [[ $# != 4 ]]
	then cmd_usage "ca.crt cakey.pem /CN=common-name days < pubkey.pem > cert.crt" 1>&2; exit 1
	fi

	CA=$1
	CAKEY=$2
	SUBJ=$3
	DAYS=$4

	exec openssl x509 -req -CA "$CA" -CAkey "$CAKEY" -copy_extensions copyall -days "$DAYS" -force_pubkey /dev/stdin \
		-in <(openssl genrsa | openssl req -new -batch -subj "$SUBJ" -key /dev/stdin -addext keyUsage=keyAgreement)
}

function do_showcert() {
	if [[ $# > 0 ]]
	then cmd_usage "< cert.crt" 1>&2; exit 1
	fi

	exec openssl x509 -text -noout -in /dev/stdin
}

function do_showcertsubject() {
	if [[ $# > 0 ]]
	then cmd_usage "< cert.crt" 1>&2; exit 1
	fi

	exec openssl x509 -subject -noout -in /dev/stdin | sed 's/^subject=//'
}

function do_showcertpubkey() {
	if [[ $# > 0 ]]
	then cmd_usage "< cert.crt" 1>&2; exit 1
	fi

	exec openssl x509 -pubkey -noout -in /dev/stdin
}

function do_verifycert() {
	if [[ $# != 1 ]]
	then cmd_usage "ca.crt < cert.crt" 1>&2; exit 1
	fi

	CA=$1

	exec openssl verify -trusted "$CA"
}

function do_gencakey() {
	if [[ $# > 0 ]]
	then cmd_usage "> cakey.pem" 1>&2; exit 1
	fi

	exec openssl genrsa
}

function do_gencacert() {
	if [[ $# != 2 ]]
	then cmd_usage "/CN=common-name days < cakey.pem > cert.crt" 1>&2; exit 1
	fi

	SUBJ=$1
	DAYS=$2

	exec {cacnffd}<<-EOF
		subjectKeyIdentifier=hash
		authorityKeyIdentifier=keyid:always,issuer
		basicConstraints=critical,CA:true
		keyUsage=cRLSign,keyCertSign
	EOF

	exec openssl x509 -new -subj "$SUBJ" -key /dev/stdin -extfile /dev/fd/$cacnffd -days "$DAYS"
}

case "$CMD" in
genkey) do_genkey "$@";;
pubkey) do_pubkey "$@";;
toraw) do_toraw "$@";;
fromraw) do_fromraw "$@";;
fromrawpub) do_fromrawpub "$@";;
showkey) do_showkey "$@";;
showpubkey) do_showpubkey "$@";;
gensignedcert) do_gensignedcert "$@";;
showcert) do_showcert "$@";;
showcertsubject) do_showcertsubject "$@";;
showcertpubkey) do_showcertpubkey "$@";;
verifycert) do_verifycert "$@";;
gencakey) do_gencakey "$@";;
gencacert) do_gencacert "$@";;
help|--help|-h|"-?") usage;;
*) usage 1>&2; exit 1;;
esac
