name: Rust-visaservice

on:
  push:
    branches: [ "main" ]
    paths:
      - 'vs-admin/**'
      - 'admin-api-types/**'
      - 'libeval/**'
      - '.github/workflows/vs-tools.yml'
      - 'Cargo.toml'
      - 'Cargo.lock'
  pull_request:
    paths:
      - 'vs-admin/**'
      - 'admin-api-types/**'
      - 'libeval/**'
      - '.github/workflows/vs-tools.yml'
      - 'Cargo.toml'
      - 'Cargo.lock'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build-vs:
    name: ${{ matrix.target }}
    strategy:
      matrix:
        target: [vs-admin, admin-api-types, libeval]
    uses: org-zpr/zpr-dev-tools/.github/workflows/rust-containerized-build-test.yml@v1.2
    with:
      name: ${{ matrix.target }}
      path: ./${{ matrix.target }}
    secrets: inherit
