name: Rust-visaservice

on:
  push:
    branches: [ "main" ]
    paths:
      - 'vs-admin/**'
      - '.github/workflows/vs-tools.yml'
  pull_request:
    paths:
      - 'vs-admin/**'
      - '.github/workflows/vs-tools.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build-vs:
    name: ${{ matrix.target }}
    strategy:
      matrix:
        target: [vs-admin]
    uses: org-zpr/zpr-dev-tools/.github/workflows/rust-containerized-build-test.yml@c4bf03c27fc14ac08cdb1b8a8c49de91f21786a7
    with:
      name: ${{ matrix.target }}
      path: ./${{ matrix.target }}
    secrets: inherit
