name: Check, Test and Build V2VS 

on:
  push:
    branches: [ "main" ]
    paths:
      - 'vs/**'
      - 'libeval/**'
      - 'admin-api-types/**'
      - '.github/workflows/vs2'
      - 'Cargo.toml'
      - 'Cargo.lock'
  pull_request:
    paths:
      - 'vs/**'
      - 'libeval/**'
      - 'admin-api-types/**'
      - '.github/workflows/vs2'
      - 'Cargo.toml'
      - 'Cargo.lock'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  CARGO_NET_GIT_FETCH_WITH_CLI: true

jobs:
  check:
    name: V2VS
    uses: org-zpr/zpr-dev-tools/.github/workflows/rust-build-test.yml@v1.1
    with:
      name: 'New New Visa Service'
      runs-on: "['ubuntu-latest']"
      needs-capnp: true
      path: 'vs/'
    secrets: inherit
