name: Rust-zpt

on:
  push:
    branches: [ "main" ]
    paths:
      - 'zpt/**'
      - 'libeval/**'
      - '.github/workflows/zpt.yml'
  pull_request:
    paths:
      - 'zpt/**'
      - 'libeval/**'
      - '.github/workflows/zpt.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  integ-test:
    name: zpt-test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v5

    - run: rustup toolchain install stable --profile minimal

    - uses: Swatinem/rust-cache@f13886b937689c021905a6b90929199931d60db1 # v2
      with:
        workspaces: zpt

    - name: Build ZPT
      timeout-minutes: 5
      working-directory: zpt
      run: cargo build --verbose

    - name: ZPT Test
      timeout-minutes: 5
      run: ./integration-test/zpt-test.sh





